### ISSUE TITLE
apk corrupted?

### ISSUE THREAD

**Issue by LaloMores** [risetechnologies/cookieTest#1]
What I've done

1. cloned this
2. meteor npm install
3. meteor
This runs ok and the tests pass in the browser (Chrome)

Then:
4. meteor build ./ --server=127.0.0.1:3000 
5. sent apk (unsigned) to phone
6. attempt to install

There I get an error message similar to "the application is corrupted" or so. Couldn't get it to install.
Context: I test unsigned APKs all the time in my phone.

Ideas?

**Comment by menelike** [comment]
Does it work when you run this project on an android virtual device with `npm run start:android`? 

*Note: You should set up a virtual device before you run this.*

**Comment by LaloMores** [comment]
I've never used virtual devices, but you gave me the idea of running directly on the device from the console.
`meteor run android-device`

Which threw the following:

```
I20191022-00:18:24.038(-3)? expected: undefined
I20191022-00:18:24.058(-3)? got: undefined
I20191022-00:18:24.059(-3)? PASS
I20191022-00:18:24.119(-3)? expected: undefined
I20191022-00:18:24.120(-3)? got: undefined
I20191022-00:18:24.120(-3)? PASS
W20191022-00:18:24.161(-3)? (STDERR) expected: __TEST_COOKIE__=1571714304237
W20191022-00:18:24.162(-3)? (STDERR) got: undefined
I20191022-00:18:24.162(-3)? FAIL
I20191022-00:18:24.185(-3)? expected: undefined
I20191022-00:18:24.185(-3)? got: undefined
I20191022-00:18:24.186(-3)? PASS
```

Plus a long list of debugger enabled stuff.
In the phone, I see a single red the test: 'server received cookie after send()'

**Comment by dr-dimitru** [comment]
@LaloMores any news have you found a solution?

@menelike did you successfully ran tests on virtual device?

**Comment by menelike** [comment]
@dr-dimitru @LaloMores 

Sorry for the late reply. My initial tests were done on an virtual android device. Today I made some tests with real devices:

Android: 
`ROOT_URL=http://yourLocalServer.localnet:3001 meteor run android-device --port 3001 --mobile-server http://yourLocalServer.localnet:3001`
![screen](https://user-images.githubusercontent.com/4238881/67680467-9493df00-f98b-11e9-844c-dd057043fc25.png)

iPhone (iOS 12.4.2 (16G114)):
`ROOT_URL=http://yourLocalServer.localnet:3001 meteor run ios-device --port 3001 --mobile-server http://yourLocalServer.localnet:3001`
![Screen Shot 2019-10-28 at 15 39 03](https://user-images.githubusercontent.com/4238881/67687820-27874600-f999-11e9-82cc-1ac8337c48bf.png)


### I am having troubles testing on iOS 13, something has changed and I have no idea what. I am in the progress of troubleshooting/fixing.
iPhone (iOS 13.1.3 (17A878)):
![Screen Shot 2019-10-28 at 15 46 54](https://user-images.githubusercontent.com/4238881/67688485-328ea600-f99a-11e9-8638-4fe81996c021.png)

**Comment by menelike** [comment]
Here we go: https://bugs.webkit.org/show_bug.cgi?id=200857

**Comment by menelike** [comment]
@dr-dimitru @LaloMores 

Sorry for the delay, I had to set up a completely new system for this (iOS 13.2 is only available on Xcode_11.2_beta_2 which made it necessary to upgrade from high sierra to mojave/catalina).

I can confirm that iOS 13.2 (17B84) fixed the cookie issue mentioned above, we're good to go! 🚀

![Screen Shot 2019-10-31 at 17 10 17](https://user-images.githubusercontent.com/4238881/67965036-95ce4180-fc01-11e9-8312-5ee600bb689c.png)
