### ISSUE TITLE
Cookies not being removed

### ISSUE THREAD

**Issue by menelike** [risetechnologies/cookieTest#2]
With the new Proxy on iOS we can workaround ITP, but removing cookies does not work at all (no timing/await/async issue).

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-18 at 21 59 43](https://user-images.githubusercontent.com/4238881/118716148-cc3fd180-b824-11eb-96a9-791178f8d85b.png)

Also, the callbacks don't work (cookies are being cleared asynchronously), see 

https://github.com/risetechnologies/cookieTest/blob/f9750c680c2fddd36f09083d53f9035e07ff0e02/client/main.js#L142-L144

and 

https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/blob/0e5bfc9274759e0a2af9c89072a59a7230c9dc15/src/ios/WebviewProxy.m#L107

Unfortunately, the completionHandler is not being used, so this resolves the issue with the callback not being called, but the async issue needs to be tackled as well.

**Comment by dr-dimitru** [comment]
Hello @menelike ,

Thank you for testing and opening this one. Got a few questions:
1. What's "ITP"?
2. Could you point me to document or briefly describe how to launch an app in 2021 (real device/sim)?
3. Android remained intact?

**Comment by menelike** [comment]
Hi @dr-dimitru,

it's been a while, nice to see/hear you 😀

> 1. What's "ITP"?

`ITP` stands for `Intelligent Tracking Prevention`. In short, it means that cross-site cookies are not allowed.
This should usually be no issue for us as we only use one domain, but in Meteor we use `localhost` (internal Meteor webapp caching server) and our real domain together. As a result, iOS won't reply with server set cookies anymore.
In theory, we should able to use [app-bound-domains](https://webkit.org/blog/10882/app-bound-domains/) to tackle this, but I could not get this to work.

I am still not sure if this could be just a configuration issue, but since Meteor itself does not use cookies there won't be any support for this on the Meteor side.
One thing I absolutely don't understand is that with Meteor [sticky sessions](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html) set by load balancers should not work anymore as well (this should be actually an interest for Meteor).

Those two links explain the issue very well:

https://github.com/apache/cordova-ios/issues/922
https://blog.merzlabs.com/posts/webview-history/

> 2. Could you point me to document or briefly describe how to launch an app in 2021 (real device/sim)?

Actually `npm run start:ios` should do the job if you've set up all [prerequisites](https://guide.meteor.com/cordova#installing-prerequisites-ios). Of course this only works on mac. `npm run start:android` runs this on Android (not only on mac of course).
Also, make sure to use Xcode >= 12.x (which is also required for the app store since April this year, prior a temporary workaround to this issue was to use Xcode 11.x)

>  3. Android remained intact?

I need to fix the tests for Android, but nothing has changed there **yet**. We can expect Android add something similar to `ITP`. Hopefully the same approach will work on Android as well https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/pull/1

-------

If you need help to setup/run this project on iOS feel free to ask, I'm glad to help out.

**Comment by menelike** [comment]
This issue has been solved in https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/pull/15
